// Code generated by "stringer -type=ErunRet"; DO NOT EDIT

package erun

import "fmt"

const _ErunRet_name = "ErunRetSuccessErunRetErrorCommandLineErunRetErrorPrepErunRetErrorClientErunRetErrorLongIoErunRetErrorParamsErunRetErrorDataVerifError"

var _ErunRet_index = [...]uint8{0, 14, 37, 53, 71, 89, 107, 133}

func (i ErunRet) String() string {
	if i < 0 || i >= ErunRet(len(_ErunRet_index)-1) {
		return fmt.Sprintf("ErunRet(%d)", i)
	}
	return _ErunRet_name[_ErunRet_index[i]:_ErunRet_index[i+1]]
}
