package sfs2014

const template = `BENCHMARK={{.Sfs2014.Benchmark}}
LOAD={{.Sfs2014.Load}}
INCR_LOAD={{.Sfs2014.IncrLoad}}
NUM_RUNS={{.Sfs2014.NumberOfRuns}}
CLIENT_MOUNTPOINTS={{range $i, $host := .Loaders}} {{$host}}:/mnt/  {{end}}
EXEC_PATH="/opt/sfs2014/sfs2014/bin/netmist"
USER="root"
WARMUP_TIME={{.Sfs2014.WarmupTime}}
IPV6_ENABLE=0
PRIME_MON_SCRIPT=
PRIME_MON_ARGS=
NETMIST_LOGS=/var/log/netmist
PASSWORD=
RUNTIME={{.Sfs2014.Runtime}}
WORKLOAD_FILE=
OPRATE_MULTIPLIER=
CLIENT_MEM=1g
AGGR_CAP=1g
FILE_SIZE=
DIR_COUNT=10
FILES_PER_DIR=100
UNLINK_FILES=0
LATENCY_GRAPH=1
HEARTBEAT_NOTIFICATIONS=1
DISABLE_FSYNCS=0
USE_RSHRCP=0
BYTE_OFFSET=0
MAX_FD=
PIT_SERVER=
PIT_PORT=
LOCAL_ONLY=0
FILE_ACCESS_LIST=0
SHARING_MODE=0
SOCK_DEBUG=0
TRACEDEBUG=0`
