package rpc2

// Define a convenient Auth interface to transparently handle different auth types.
//
// The autogenerated code includes only AuthUnix and OpaqueAuth which are not convenient,
// since they require manual XDR encoding.

type Auth interface {
	isAuth()
}

type AuthNull struct{}

func (*AuthUnix) isAuth() {}
func (*AuthNull) isAuth() {}

func NewAuthUnix(uid, gid int) *AuthUnix {
	return &AuthUnix{
		Uid:  uint32(uid),
		Gid:  uint32(gid),
		Gids: []uint32{uint32(gid)},
	}
}
