// Code generated by "stringer -type=FCRet"; DO NOT EDIT

package fstool_config

import "fmt"

const _FCRet_name = "FCRetSuccessFCRetErrorBadConfigFCRetErrorNFSClientFCRetErrorRootDirFCRetErrorFSInfoFCRetErrorWorkDirFCRetErrorToolFCRetErrorPanic"

var _FCRet_index = [...]uint8{0, 12, 31, 50, 67, 83, 100, 114, 129}

func (i FCRet) String() string {
	if i < 0 || i >= FCRet(len(_FCRet_index)-1) {
		return fmt.Sprintf("FCRet(%d)", i)
	}
	return _FCRet_name[_FCRet_index[i]:_FCRet_index[i+1]]
}
